### ISSUE TITLE
Question about the 'GT_Depth'

### ISSUE THREAD

**Issue by rcao-hk** [junyang224/ROBI_Toolkit#1]
Hi,

Thank you for your work.

I have a question about ROBI dataset. I noticed folder 'GT_Depth', the index of images in this folder is not matched with the index in the sensor's folders. Is there any relationship between images from GT_Depth and images from the sensor's folders? What is the function of it?

Regards,
Rui

**Comment by junyang224** [comment]
Hello Rui,

Thanks for the question.

For the GT depth, we didn't capture all the viewpoints. Here is the relationship between GT_Depth and Ensenso sensor folder:

For Scene 1-3:
**GT_Depth**: view_0---view_16   --->   **Ensenso/Depth**: DEPTH_view_71---DEPTH_view_87

For Scene 4-5:
**GT_Depth**: view_0---view_105   --->   **Ensenso/Depth**: DEPTH_view_0---DEPTH_view_105

For Scene 6-7:
**GT_Depth**: view_0---view_2   --->   **Ensenso/Depth**: DEPTH_view_12---DEPTH_view_14
**GT_Depth**: view_3   --->   **Ensenso/Depth**: DEPTH_view_16
**GT_Depth**: view_4   --->   **Ensenso/Depth**: DEPTH_view_18
**GT_Depth**: view_5   --->   **Ensenso/Depth**: DEPTH_view_22
**GT_Depth**: view_6   --->   **Ensenso/Depth**: DEPTH_view_24
**GT_Depth**: view_7---view_23   --->   **Ensenso/Depth**: DEPTH_view_25---DEPTH_view_41

For Scene 8-9:
**GT_Depth**: view_0---view_67   --->   **Ensenso/Depth**: DEPTH_view_0---DEPTH_view_67

We will keep working on the dataset, and will have a better data organization before the IROS conference this year.

Thanks
Jun

**Comment by rcao-hk** [comment]
> Hello Rui,
> 
> Thanks for the question.
> 
> For the GT depth, we didn't capture all the viewpoints. Here is the relationship between GT_Depth and Ensenso sensor folder:
> 
> For Scene 1-3:
> **GT_Depth**: view_0---view_16 ---> **Ensenso/Depth**: DEPTH_view_71---DEPTH_view_87
> 
> For Scene 4-5:
> **GT_Depth**: view_0---view_105 ---> **Ensenso/Depth**: DEPTH_view_0---DEPTH_view_105
> 
> For Scene 6-7:
> **GT_Depth**: view_0---view_2 ---> **Ensenso/Depth**: DEPTH_view_12---DEPTH_view_14
> **GT_Depth**: view_3 ---> **Ensenso/Depth**: DEPTH_view_16
> **GT_Depth**: view_4 ---> **Ensenso/Depth**: DEPTH_view_18
> **GT_Depth**: view_5 ---> **Ensenso/Depth**: DEPTH_view_22
> **GT_Depth**: view_6 ---> **Ensenso/Depth**: DEPTH_view_24
> **GT_Depth**: view_7---view_23 ---> **Ensenso/Depth**: DEPTH_view_25---DEPTH_view_41
> 
> For Scene 8-9:
> **GT_Depth**: view_0---view_67 ---> **Ensenso/Depth**: DEPTH_view_0---DEPTH_view_67
> 
> We will keep working on the dataset, and will have a better data organization before the IROS conference this year.
> 
> Thanks
> Jun

Thank you for your reply.

**Comment by junyang224** [comment]
The dataset has been updated, the indices of GT depth map now corresponds to the correct depth map in Ensenso fodler.
