### ISSUE TITLE
About roi 

### ISSUE THREAD

**Issue by xumingkun9806** [junyang224/ROBI_Toolkit#4]
hello,I want to ask how to get the box mak,like this,do you have sample way? Thank you!
![image](https://user-images.githubusercontent.com/61106108/172101430-5f2a16a5-c682-4e5b-9fb6-6f15ce7cea72.png)

**Comment by junyang224** [comment]
Hello, I don't quite understand "box mak", can you please be more specific?

Thanks

**Comment by xumingkun9806** [comment]
I mean I want to get the object area depth fot pointcloud,do you have a easier way to do this than manually cutting

**Comment by junyang224** [comment]
Hello, one simple way is to manually define a global 3D ROI of the bin area at the "world coordinate", then for each view depth map, transform the 3D point cloud to the world frame (using known extrinsics) and crop the point cloud using the defined ROI.

You may need to define the global ROI for each bin scene, which can be applied to each viewpoint data with same bin scene.

**Comment by xumingkun9806** [comment]
OK,I know,thak you!
