### ISSUE TITLE
visibility score

### ISSUE THREAD

**Issue by doublechenchen** [junyang224/ROBI_Toolkit#5]
Sorry to interrupt, where to download the associated visibility score of visible objects.

**Comment by junyang224** [comment]
Hello Chen:

Thanks for pointing out this issue! 

Unfortunately, the visibility score is not available is currently not available. The visibility score should be associated with the ground truth object pose and defined under camera coordinate. However, in the current version of ROBI dataset, we provide the ground truth under world frame.

We will start working on the ROBI dataset for this issue and expect to provide the visibility score in one or two weeks.

Thank you
Jun

**Comment by junyang224** [comment]
Hello:

The visibility score has been added to the ROBI dataset, for each viewpoint image, we add the visibility score for each object, as shown below.

Please let me know if you have any questions.

{"cam_pose": [0.944755, -0.079584, 0.317969, -182.902, 0.002751, -0.968118, -0.250479, 84.6171, 0.327765, 0.237516, -0.914415, 346.799, 0.0, 0.0, 0.0, 1.0]}
{"object_1_visibility": 1.0}
{"object_2_visibility": 1.0}
{"object_3_visibility": 0.8380211780277962}
{"object_4_visibility": 0.999162198391421}
{"object_5_visibility": 0.887160877829618}
{"object_6_visibility": 0.7008443908323281}
{"object_7_visibility": 0.9950504473634114}
{"object_8_visibility": 0.9623793578885168}
{"object_9_visibility": 0.5995697602950215}
{"object_10_visibility": 0.36064605081741186}
{"object_11_visibility": 0.35650527454692993}
{"object_12_visibility": 0.25554278206602066}
{"object_13_visibility": 0.5583318972945028}

**Comment by doublechenchen** [comment]
thank you
