### ISSUE TITLE
How to get the objects' 6D pose relative to the camera?

### ISSUE THREAD

**Issue by WeichenFan** [junyang224/ROBI_Toolkit#7]
Hi, thank you for your work!

I am wondering how to get the objects' 6D pose in camera coordinates.

Thanks in advance!

**Comment by junyang224** [comment]
Hello:

We first label the object poses in the world coordinate by:
   "We performed the alignment process using MeshLab [31]. We first manually aligned object models to the scene model as an 
   initial 6D object pose estimate. We then upsampled the CAD model to a high resolution, and applied ICP to refine the object 
   pose. Lastly, we adjusted the pose manually whenever necessary to correct any inplane translation and rotation."

The object poses can be transformed to the camera coordinate using known camera poses.

Thanks
Jun

**Comment by junyang224** [comment]
Hello:

In the ROBI dataset, we provide the object poses in the world coordinate (transformation from object frame to world frame): T_w2o.

To get the object poses in the camera coordinates T_c2o, you need to use the provided camera poses T_w2c:
T_c2o = T_c2w * T_w2o

Thanks
Jun

**Comment by WeichenFan** [comment]
Thank you for your reply!
